CREATE TABLE userProfile(
userID INT PRIMARY KEY AUTO_INCREMENT,
username VARCHAR(20) NOT NULL,
password VARCHAR(20) NOT NULL
);

CREATE TABLE wishList(
wishListID INT PRIMARY KEY AUTO_INCREMENT,
title VARCHAR(100) NOT NULL,
description VARCHAR(300) NOT NULL,
userID INT,
FOREIGN KEY(userID) REFERENCES userProfile(userID) ON DELETE CASCADE
);

CREATE TABLE wish(
wishID INT PRIMARY KEY AUTO_INCREMENT,
title VARCHAR(100) NOT NULL,
number INT NOT NULL,
price INT NOT NULL,
link VARCHAR(300) NOT NULL,
description VARCHAR(300) NOT NULL,
wishListID INT,
FOREIGN KEY(wishListID) REFERENCES wishList(wishListID) ON DELETE CASCADE
);

CREATE TABLE reservation(
wishID INT,
userID INT,
number INT NOT NULL,
FOREIGN KEY(userID) REFERENCES userProfile(userID) ON DELETE CASCADE,
FOREIGN KEY(wishID) REFERENCES wish(wishID) ON DELETE CASCADE,
PRIMARY KEY (wishID, userID)
);